digiquip/dq-website

docs/legal/privacy-policy.md
=> Endret heading

i18n/nb/code.json, src/pages/about/index.js, src/pages/modellibrary/index.js
Some minor fixes for bugs found after the page was released
=> Minor fixes

blog/2024-03-04-opplæring/index.md, docusaurus.config.js, src/theme/Navbar/Content/index.js
1. Change header to blogg
2. Fixed slug on blog-article
3. Added the price page
=> Fixed minor stuff

src/pages/price/index.js
Price calc. fixes and link from subscription page to detailed prices:
-Range
-Link to more details for prices plus labels
=> Price calc. fixes and link from subscription page to detailed prices 

blog/2024-04-12-lover-og-regler/index.md
=> Change of video, Lars article

src/css/custom.css
The font "jakartasans" was not present as a font, but still referenced in the CSS. Changed to inter
=> Wrong font in calc

blog/2024-03-10.md, blog/2024-04-25-poncat/index.md, data/eventContent.js, data/mainPageContents.js, i18n/en/code.json, i18n/en/docusaurus-plugin-content-blog/2024-03-10.md, i18n/nb/code.json, src/components/Layout1/index.js, src/pages/event/index.js, src/pages/index.js, yarn.lock
The event block and page is now present, but hidden.
=> Temporary remove event block and fix typos

docs/prices/detailed-price-list.md, src/pages/price/index.js
- Updated prices 
- Added a landing page for the the contact us action :-)
=> Price updates

docusaurus.config.js
=> Fixed documentation link

blog/2024-04-12-lover-og-regler/index.md, docs/resources/landingpage.md, docs/resources/training.md, docs/resources/user-management.md
Gjenstår en youtube video på forsiden
=> Fjernet youtube videoer under "FAQ" - delen

i18n/en/code.json, src/css/custom.css
=> Add news translation in en file

data/mainPageContents.js
Feil url under "Full kontroll på arbeidsutstyr og dokumentasjon" oppdatert url slik at du bli sendt til trygg maskin
=> Oppdatert url

src/css/custom.css, src/pages/price/index.js
- Prices in Elfsight price widget.
- Removed KREG and MREG as a list of integrations. For now just a sentence about that we know integrations..
=> Elfsight price matrix

blog/2024-04-25-poncat/index.md, data/partnersBrandLogo.js
=> AF partner logo

docs/KVIPP/equipment.md, docs/prices/detailed-price-list.md, i18n/en/docusaurus-plugin-content-docs/current/Kvipp/equipment.md, i18n/en/docusaurus-plugin-content-docs/current/Kvipp/get_started.md, i18n/en/docusaurus-plugin-content-docs/current/Kvipp/people.md, i18n/en/docusaurus-plugin-content-docs/current/Kvipp/stuff.md, i18n/en/docusaurus-plugin-content-docs/current/prices/detailed-price-list.md
-Equipment: Seach and add manually
-Persons: Provide training on multiple asset types in one session
=> Docs: English versions

docusaurus.config.js
=> Hiding Theme Switch Button

docs/DigiQuip/inspections.md, docs/product/mar25.md, i18n/en/docusaurus-plugin-content-docs/current/DigiQuip/inspections.md, i18n/en/docusaurus-plugin-content-docs/current/product/mar25.md
Updated Release notes page with changes
=> Release notes Inspect

blog/2025-03-26-webinar-AF-betonmast/index.md, i18n/nb/code.json
=> Minor text changes about webinar 8th April

blog/2025-03-26-webinar-AF-betonmast/index.md, i18n/en/code.json, i18n/nb/code.json
**Webinar 8th April**
News front page:  From coming-up to completed. 
Blog: From coming-up to completed: Added the video, the campaign offer, contact informations and the book demo form.
=> Webinar update 8th April

blog/2025-03-25-dokumentere-rutiner-og-opplaering/index.md, blog/2025-03-26-webinar-AF-betonmast/index.md, blog/2025-04-11-geirschau/index.md, data/mainPageContents.js, i18n/en/code.json, i18n/nb/code.json
-Geir Schau video on the main page
=> Added Geir Schau on the front page

package-lock.json, package.json, src/pages/bedrift/index.js, src/pages/kvipp/index.js, yarn.lock
-Added the demo-form via Elfsight on the product pages Kvipp and Kvipp Bedrift
-The setup was created copied from Elfsight developer's setup and includes adding elfsight react widget apps "for simpler implementations later on"
=> Added demo-form (via Elfsight) Kvipp and Bedrift pages

docs/prices/detailed-price-list.md, i18n/en/docusaurus-plugin-content-docs/current/prices/detailed-price-list.md
-Added services 1400 NOK per hour
-Added services as a package 4990 NOK 
No. and En. version.
=> Updated prices (docs) with services

docs/KVIPP/people.md, docs/product/mar25.md, i18n/en/docusaurus-plugin-content-docs/current/Kvipp/handover.md, i18n/en/docusaurus-plugin-content-docs/current/Kvipp/people.md, i18n/en/docusaurus-plugin-content-docs/current/product/mar25.md
Added send email as a new feature in lessons. Docs pages:
-Release notes
-Kvipp > people > note to the lesson section
=> Release notes and small update docs: send email

docusaurus.config.js, i18n/en/code.json, i18n/en/docusaurus-theme-classic/navbar.json, i18n/nb/code.json, i18n/nb/docusaurus-theme-classic/navbar.json, src/css/custom.css, src/pages/signin/index.js
New page for selecting which service to sign in to. 
1.Kvipp
2.DigiQuip
3.Reach out for getting access
=> Sign-in page with choose service

i18n/en/docusaurus-theme-classic/navbar.json, i18n/nb/docusaurus-theme-classic/navbar.json
Fixed the "Prices" and "Documentation"
=> Fix English texts in the main navigation bar

src/css/custom.css, src/pages/contact/index.js
-decreased text size: too large!
-max width for contact cards: So that it does not expand too much on wide screens
=> Decreased text size in the nav bar and added a max width for contact cards

data/OrderPolicyForm.js, src/css/custom.css, src/pages/bestill-policy.js
Independent page for ordering policy:
-What it is 
-Form 
Missing: 
-For who 
-What's the price if not part of the 10 first who signs up for it
No links to this page from other pages, therefore it can be tested live.
=> Bestill-policy side (kun norsk)

src/pages/bestill-policy.js
Page /bestill-policy
Moved placement of video to start of page, immediately after main heading.
=> Page bestill-policy: Moved the placement of video
